<a href="https://colab.research.google.com/github/17092003vamsi/213ECE3317/blob/main/213ECE3317.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
primes = tf.constant([2, 3, 5, 7, 11, 14 , 13 ,12], dtype=tf.int64)
print("primes:", primes)
ones = tf.ones([8], dtype=tf.int64)
print("ones:", ones)
just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2, 2, 2], dtype=tf.int64)
primes_doubled = primes * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=tf.int64)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
primes: tf.Tensor([ 2  3  5  7 11 14 13 12], shape=(8,), dtype=int64)
ones: tf.Tensor([1 1 1 1 1 1 1 1], shape=(8,), dtype=int64)
just_beyond_primes: tf.Tensor([ 3  4  6  8 12 15 14 13], shape=(8,), dtype=int64)
primes_doubled: tf.Tensor([ 4  6 10 14 22 28 26 24], shape=(8,), dtype=int64)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int64)

value of some_matrix is:
 [[1 2 3 4]
 [5 6 7 8]]


In [7]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")

11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1500/1500 [==============================] - 10s 5ms/step - loss: 0.2775 - accuracy: 0.9210 - val_loss: 0.1447 - val_accuracy: 0.9574
Epoch 2/5
1500/1500 [==============================] - 9s 6ms/step - loss: 0.1177 - accuracy: 0.9632 - val_loss: 0.1065 - val_accuracy: 0.9678
Epoch 3/5
1500/1500 [==============================] - 9s 6ms/step - loss: 0.0810 - accuracy: 0.9745 - val_loss: 0.0944 - val_accuracy: 0.9708
Epoch 4/5
1500/1500 [==============================] - 8s 6ms/step - loss: 0.0608 - accuracy: 0.9812 - val_loss: 0.0946 - val_accuracy: 0.9730
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0875 - accuracy: 0.9746
Test accuracy: 0.9746


In [8]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")

Epoch 1/5
1500/1500 [==============================] - 11s 7ms/step - loss: 0.2662 - accuracy: 0.9222 - val_loss: 0.1433 - val_accuracy: 0.9563
Epoch 2/5
1500/1500 [==============================] - 7s 5ms/step - loss: 0.1143 - accuracy: 0.9660 - val_loss: 0.1093 - val_accuracy: 0.9672
Epoch 3/5
1500/1500 [==============================] - 14s 9ms/step - loss: 0.0789 - accuracy: 0.9757 - val_loss: 0.0956 - val_accuracy: 0.9722
Epoch 4/5
1500/1500 [==============================] - 9s 6ms/step - loss: 0.0573 - accuracy: 0.9817 - val_loss: 0.0977 - val_accuracy: 0.9714
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0814 - accuracy: 0.9758
Test accuracy: 0.9758


In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
np.random.seed(42)
X = np.random.rand(1000, 2)
y = (X[:, 0] + X[:, 1] > 1).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = Sequential([Input(shape=(2)),Dense(64, activation='relu'),Dense(1, activation='sigmoid')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
test_accuracy = accuracy_score(y_test, y_pred_binary)
print(f"Test accuracy: {test_accuracy:.4f}")

Epoch 1/10
20/20 [==============================] - 1s 12ms/step - loss: 0.6875 - accuracy: 0.5172 - val_loss: 0.6740 - val_accuracy: 0.6125
Epoch 2/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6710 - accuracy: 0.6078 - val_loss: 0.6544 - val_accuracy: 0.6875
Epoch 3/10
20/20 [==============================] - 0s 4ms/step - loss: 0.6558 - accuracy: 0.6594 - val_loss: 0.6362 - val_accuracy: 0.7063
Epoch 4/10
20/20 [==============================] - 0s 4ms/step - loss: 0.6400 - accuracy: 0.7141 - val_loss: 0.6206 - val_accuracy: 0.7375
Epoch 5/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6235 - accuracy: 0.7563 - val_loss: 0.6032 - val_accuracy: 0.7625
Epoch 6/10
20/20 [==============================] - 0s 4ms/step - loss: 0.6050 - accuracy: 0.7875 - val_loss: 0.5851 - val_accuracy: 0.8188
Epoch 7/10
20/20 [==============================] - 0s 4ms/step - loss: 0.5844 - accuracy: 0.8047 - val_loss: 0.5645 - val_accuracy: 0.8438
Epoch 8/10
20/20 [=

In [12]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
def get_mae(max_leaf_nodes,train_X,val_X, train_y, val_y):
  model=DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes,random_state=0)
  model.fit(train_X,train_y)
  preds_val=model.predict(val_X)
  mae = mean_absolute_error(val_y,preds_val)
  return (mae )
melbourne_data=pd.read_csv('melb_data(1).csv')
filtered_melbourne_data=melbourne_data.dropna(axis=0)
y= filtered_melbourne_data.Price
melbourne_features = ['Rooms', 'Bathroom', 'Landsize' ,'BuildingArea' ,'YearBuilt' ,'Lattitude', 'Longtitude']
X= filtered_melbourne_data[melbourne_features]
train_X, val_X, train_y, val_y=train_test_split(X, y, random_state=0)
for max_leaf_nodes in [5, 50, 500, 5000]:
  my_mae=get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
  print("Max leaf nodes: %d  \t\t Mean Absolute Error: %d" %(max_leaf_nodes,my_mae) )

FileNotFoundError: ignored